import Godot from "@/components/Godot";
import Intro from "@/components/Intro";
import Three from "@/components/Three";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro />

        <style jsx>
          {`
            :global(html),
            :global(body) {
              height: 100%;
            }

            .godot {
              position: relative;
              z-index: -1;
              height: 0;
            }
          `}
        </style>
      </main>
    </>
  );
}
