import Head from "next/head";
import Godot from "@/components/Godot";

export default function Scene() {
    return (
        <>
        <Head>
            <title>Scene</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main>
            <Godot />
        </main>
        </>
    )
}
